### ISSUE TITLE
Missing Tocantins

### ISSUE THREAD

**Issue by gustavobio** [RobertMyles/congressbr#39]
Hi,

`UF()`, `statesBR`, and I'd guess all functions that aggregate data by state are missing Tocantins:

```coffee
> "TO" %in% UF()
 [1] "AC" "AL" "AP" "AM" "BA" "CE" "DF" "ES" "GO" "MA" "MT" "MS" "MG" "PA"
[15] "PB" "PR" "PE" "PI" "RJ" "RN" "RS" "RO" "RR" "SC" "SP" "SE"
[1] FALSE

> subset(statesBR, Name == "Tocantins")
# A tibble: 0 x 2
# ... with 2 variables: UF <chr>, Name <chr>
```

Thanks,

Gustavo.

**Comment by RobertMyles** [comment]
Well, look at that! Poor Tocantins. We'll get it sorted ASAP, thanks for letting us know!

**Comment by RobertMyles** [comment]
@gustavobio  Fixed now in the dev version, will b on CRAN shortly.

**Comment by gustavobio** [comment]
@RobertMyles Thanks! `sen_senator_list()` is still missing Tocantins though. Maybe a good time to call `UF()` instead?

Anyway, since people are generally interested in knowing how others are using their packages, I came across `congressBR` whilst looking for data on Brazilian deputies for a blog post idea. Learning that there is an API and an R package to go with it was a very nice surprise. I'm implementing `cham_deputy_list()` and `cham_deputy_details()` in a local fork to get some of the data I want. 

Thanks again.

**Comment by RobertMyles** [comment]
@gustavobio Thanks again, `sen_senator_list()` is fixed now. We're definitely interested in how people use the package and why, so thanks for the info. As regards the Chamber, the API is changing so soon we'll have a load of new options for the Câmara.
